twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
      - 'form/fields.html.twig'
    globals:
      resumes_uploads_path: '%resumes%'
when@test:
    twig:
        strict_variables: true
